export const GET_LEADS = 'GET_LEADS'
export const DELETE_LEAD = 'DELETE_LEAD'
export const ADD_LEAD = 'ADD_LEAD'
export const GET_ERRORS = 'GET_ERRORS'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'